### ISSUE TITLE
older versions of php are failing

### ISSUE THREAD

**Issue by arniebradfo** [mukhortov/HESH-WordPress-Plugin#10]
[line 43 of the .php file is causing pre v5.4 php to crash](https://wordpress.org/support/topic/plugin-completely-unusuable-after-update).

Its because of [this](http://php.net/manual/en/language.types.array.php#example-105
), but it takes down the whole site, so we should push an update asap.

I committed it straight to master with no PR. sorry.

**Comment by mukhortov** [comment]
1.7.2 is released
