### ISSUE TITLE
Content Resize handle has been removed

### ISSUE THREAD

**Issue by rraub** [mukhortov/HESH-WordPress-Plugin#11]
Is there a reason the content resize handle has been removed? 

If I remove [this style](https://github.com/mukhortov/HESH-WordPress-Plugin/blob/8914d47ae58aa816956b1d2d9a64d5867a4d4483/dev/hesh.dev.less#L182)  it works just fine.

**Comment by rraub** [comment]
have either of you had a change to look at this issue?  @mukhortov or @arniebradfo

**Comment by arniebradfo** [comment]
hmmm. i can still resize the window in chrome, but that selector should've disabled the control.

I agree it should be removed. Make a Pull request with those lines deleted or commented and Ill merge it.

**Comment by arniebradfo** [comment]
this is fixed in v2.0
