### ISSUE TITLE
Emmet Support

### ISSUE THREAD

**Issue by MacWordPress** [mukhortov/HESH-WordPress-Plugin#12]
Your plugin is great! Could you please add support for [Emmet](https://github.com/emmetio/codemirror).

**Comment by arniebradfo** [comment]
I didn't know there was a version of Emmet for Codemirror.

I'll experiment with adding it as a non-default option in a later version.

Thanks,
-James

**Comment by MacWordPress** [comment]
Thanks James, great news!
Adding Emmet will make HESH my WP developer's dream plugin.

**Comment by arniebradfo** [comment]
I've looked into using emmet, and the features are a little too advanced for this application. Not going to add it... Sorry
