### ISSUE TITLE
Limits editor height, thus effectively disabling in-page search

### ISSUE THREAD

**Issue by psaniko** [mukhortov/HESH-WordPress-Plugin#19]
When enabling the plugin, the height of the editor gets limited to a fixed value, so one has to scroll inside a box instead of the scrolling the whole page. For long posts this means most of the content is outside the visible scroll area and thus cannot be searched with in-page search functionality (ctrl/cmd + F).

Browser: Chrome 55.0
Wordpress: 4.5.4
HESH: 1.7.2

**Comment by arniebradfo** [comment]
So...

Yes, The browser's find functionality only works with the syntax-highlighter if you can already see the text onscreen(defeats the purpose of 'find', I know).

For versions 1.x there's no solution, but...

I have a workaround in a [version 2.0](https://github.com/mukhortov/HESH-WordPress-Plugin/releases/latest) that was just finished. I should be being released around the end of May. Until then, you can download v2.0 from this repository's releases and install it yourself.

__How to install__
1. Deactivate your current version of the _HTML Editor Syntax Highlighter_ plugin.
2. Download the `[HESH-WordPress-Plugin-2.0.0.zip](https://github.com/mukhortov/HESH-WordPress-Plugin/archive/v2.0.0.zip)`.
3. In WordPress, go to _Plugins_ > _Add New_ > _Upload Plugin_ > _Choose File_.
4. Select the `HESH-WordPress-Plugin-2.0.0.zip` file that you just downloaded.
5. Select _Install Now_ then _Activate_.

__How to Search/Find with `Ctrl/Cmd + F`__
1. On an Edit Post page, open the '_Screen Options_' tab at the top right of the page.
2. Make sure the last checkbox '_Enable full-height editor and distraction-free functionality_' is __checked__. This will allow the editor expand to the full length of the content.
3. Search with `Ctrl/Cmd + F`

I'm working on adding a find and a find+replace feature, but it won't be in the first release of v2.0. Ill leave this bug open till I add the real feature.

**Comment by arniebradfo** [comment]
version 2.0 fixes the limited editor height. 
The addition of the search feature is being tracked in #31 

closing this
