### ISSUE TITLE
No code windows on init when on WP 3.7.1

### ISSUE THREAD

**Issue by Cleanshooter** [mukhortov/HESH-WordPress-Plugin#2]
If I click "Add New" for a post or page and the if last time I was in "Text" or Code mode the editor tries to default into "Text" mode instead of Visual.  Problem is the screen doesn't display the code windows area thing.... yeah bad description I know.  

Might just be my install... can you replicate?

**Comment by arniebradfo** [comment]
not supporting <4.0.11 anymore.

sorry :(
