### ISSUE TITLE
Insert image is broken

### ISSUE THREAD

**Issue by blackboxx** [mukhortov/HESH-WordPress-Plugin#20]
Hello, when inserting an image with wordpress wysiwig, an error happens and no image displayed.
Problem can be seen in console.
Wordpress version 4.7.1 Browser Chrome MacOS

**Comment by PenskeGuy** [comment]
Confirmed. Win8.1, Firefox 52.0.1 & Chrome 57.  WP 4.7.3 w/plugs disabled.

I use the text editor only, so am unsure about wysiwig.
Workaround:
Add Media as normal
When the "Add Media" button highlight goes out, cycle the Distraction-free writing mode button
Image code appears

**Comment by arniebradfo** [comment]
This is fixed in v2.0
