### ISSUE TITLE
activeline-background?

### ISSUE THREAD

**Issue by PenskeGuy** [mukhortov/HESH-WordPress-Plugin#23]
Win8.1, Firefox 52, Chrome 57, WP 4.7.3 w/plugs disabled.

Can't seem to get a background change on the active line in any of the themes.

Other than that, It Works Great!

**Comment by arniebradfo** [comment]
This should be solved in the [v2.0 release.](https://github.com/mukhortov/HESH-WordPress-Plugin/releases/latest)

Some of the color themes don't support the background highlighting, so keep that in mind.

**Comment by arniebradfo** [comment]
This is fixed in v2.0, but some themes still don't (and never will) support background highlighting.
