### ISSUE TITLE
carbonfields support?

### ISSUE THREAD

**Issue by sanjayatony** [mukhortov/HESH-WordPress-Plugin#25]
Is there any plan to support carbonfields?

**Comment by arniebradfo** [comment]
In what way? Could you describe how the syntax highlighter would integrate with this plugin? Please provide examples/links.

There are currently plans to integrate with some popular plugins in the future, but its low on the priority list. I could add carbonfields integration to the list if I had more details.

Thanks!

**Comment by sanjayatony** [comment]
support I mean, if the custom fields is a wysiwyg(which is same like wp editor), syntax highlighter will also will highlight it..

And thanks for great plugin!

**Comment by arniebradfo** [comment]
this is tracked in #28 now
