### ISSUE TITLE
`esc` functionality

### ISSUE THREAD

**Issue by arniebradfo** [mukhortov/HESH-WordPress-Plugin#29]
what should the `esc` key do
- only exit fullscreen, not toggle it
- exit multiple cursor selection

**Comment by arniebradfo** [comment]
esc shouldn't exit mulit-cursor selection

**Comment by dallanlee** [comment]
How, then, does one exit multi-cursor selection?

**Comment by arniebradfo** [comment]
click anywhere else?

**Comment by dallanlee** [comment]
@arniebradfo I don't expect to change your mind. But I will just explain myself briefly. The HESH plugin is an attempt to make the WordPress text editor feel more like an real text editor with some power like developers are used to with Visual Studio Code, Atom, Sublime Text, etc. I love that about this plugin! So, in a text editor, a developer tends to learn their environment such that they can keep their hands on the keyboard as much as possible and very rarely use the cursor. But whatever.

**Comment by arniebradfo** [comment]
Ahhh. You want to exit multi-cursor selection without using the mouse.
Ok, so we can't use the `esc` key for that because it will exit full screen in some contexts. 

However, I could add another key command to exit multi-cursor selection. Maybe double pressing the key command the enter multi-cursor? Got any ideas?

**Comment by dallanlee** [comment]
Yeah, I see. Well, I'm not sure what a good alternative would be 🤔
