### ISSUE TITLE
When no editor is present, hesh.min.js fails

### ISSUE THREAD

**Issue by intoxstudio** [mukhortov/HESH-WordPress-Plugin#3]
hesh.min.js is loaded on all edit/post screens, even when no editor is present. This causes hesh.min.js to fail as it expects an editor element.

In is_editor(), use post_type_supports($post,'editor') to check if the editor is present.
http://codex.wordpress.org/Function_Reference/post_type_supports

Also, consider using admin_enqueue_scripts to load your scripts and styles instead of injecting them "manually".

**Comment by arniebradfo** [comment]
I implemented your suggestion.

Thanks for the advice.
