### ISSUE TITLE
Scrollbar appears in middle of text editor

### ISSUE THREAD

**Issue by kyle-charlton** [mukhortov/HESH-WordPress-Plugin#43]
I'm not sure if this is a bug or if its intentional but after updating the plugin to 2.0 I see a scrollbar in the middle of the text editor.

It appears to be caused by `overflow: scroll !important;` set on **.CiodeMirror-Scroll** in `/wp-content/plugins/html-editor-syntax-highlighter/dist/hesh.css?ver=2.0.0` on line 213.

When I turn off the overflow scroll the text editor looks fine.

![scrollbar-error](https://user-images.githubusercontent.com/12102133/26850126-51de2de0-4abb-11e7-800b-02cf46adf835.PNG)

**Comment by arniebradfo** [comment]
Yea that doesn't look good.

What's your OS and browser?

**Comment by arniebradfo** [comment]
Fixed in [v2.0.1](https://github.com/mukhortov/HESH-WordPress-Plugin/releases/tag/v2.0.1).
