### ISSUE TITLE
Quicktags toolbar can hide HESH settings if there are too many tags

### ISSUE THREAD

**Issue by JoshuaTurner-Bruce** [mukhortov/HESH-WordPress-Plugin#45]
![screenshot](https://user-images.githubusercontent.com/29600545/27382705-ee32d54a-567f-11e7-90bf-82d0370079b0.jpg)

**Comment by arniebradfo** [comment]
HA! you've got a lot of buttons there.

What plugin are you using to add those shortcode buttons?

**Comment by JoshuaTurner-Bruce** [comment]
It's a part of the theme, just using the quicktags API. 

I think the issue may be that you are collecting the height of the qtags toolbar for your toolbar offset before any custom quicktags are loaded?

**Comment by arniebradfo** [comment]
Fixed in [v2.0.1](https://github.com/mukhortov/HESH-WordPress-Plugin/releases/tag/v2.0.1).
