### ISSUE TITLE
Selected area is barely seen

### ISSUE THREAD

**Issue by ophirh2** [mukhortov/HESH-WordPress-Plugin#46]
First, thank for this great plug-in

In all the themes i tried, the "selected" area is barely seen. This makes the usage of "copy" & "paste" very problematic. Thanks.

**Comment by arniebradfo** [comment]
This is an issue with the themes. I agree, a lot of them are not great, but I can't change those. 

I do, however, have plans to write my own theme set that is wordpress specific. Thats here: #37

I'll keep the contrast in mind when I design the themes.

Thanks!
