### ISSUE TITLE
GitHub Updater Integration problem

### ISSUE THREAD

**Issue by afragen** [mukhortov/HESH-WordPress-Plugin#52]
I am the developer of GitHub Updater and I see you have added support to this plugin. There is, however, a problem. It is characterized in the more recent comments to this issue, https://github.com/afragen/github-updater/issues/581#issuecomment-326982177

The problem arises in that the repository name `HESH-WordPress-Plugin` and dot org’s slug `html-editor-syntax-highlighter` are not identical. As such, when the plugin is installed via dot org it is placed in a directory `wp-content/plugins/html-editor-syntax-highlighter`, if it is ever updated using GitHub Updater this will be renamed according to the repository name, `wp-content/plugins/HESH-WordPress-Plugin` and will never be updatable from dot org again.

My suggestion would be to rename the repository here to match the dot org slug. LMK if you have any questions or issues I can help with.

Also, branch headers are no longer required as the branch is set during an installation via GitHub Updater or during a branch switch.

**Comment by arniebradfo** [comment]
I forgot to remove that from the production version. Thanks for the heads-up. It'll be fixed in the next patch.

And Thanks a lot for making such an awesome plugin. The github updater is the best!
