### ISSUE TITLE
Добавьте поддержку Emmet

### ISSUE THREAD

**Issue by mihdan** [mukhortov/HESH-WordPress-Plugin#53]
Emmet - архиважное и архиполезное дополнение для любого уважающего себя текстового редактора для разворачивания абривиатур. CodeMirror является таким, поэтому под него @sergeche (Сергей Чикуёнок, автор Emmet) сделал дополнение ~~https://github.com/emmetio/codemirror~~ и вторая версия https://github.com/emmetio/codemirror-plugin

**Comment by sergeche** [comment]
Лучше вот этот: https://github.com/emmetio/codemirror-plugin
Он по-новее и покруче

**Comment by mihdan** [comment]
Сергей, реально, вторая версия круче, обновил у себя везде

**Comment by marcusig** [comment]
I agree (I think 😄 )! Emmet would be an awesome addition!

**Comment by arniebradfo** [comment]
Closing this one in favor of the one in english #76 . Sorry comrades.
