### ISSUE TITLE
Conflicts with Wordpress 4.9

### ISSUE THREAD

**Issue by gr8shivam** [mukhortov/HESH-WordPress-Plugin#56]
The plugin works perfectly in Post text highlighting but conflicts with Wordpress 4.9 Syntax Highlighting feature for Theme & Plugin editor.

<img width="1040" alt="screen shot 2017-11-20 at 12 37 26 pm" src="https://user-images.githubusercontent.com/4292333/33006272-bf7d96da-cdef-11e7-9858-5f8c946a5bb4.png">

**Comment by arniebradfo** [comment]
I'll fix this soon.

**Comment by gr8shivam** [comment]
Would be great if we can utilise the Codemirror.js from Wordpress installation if WP version is greater than 4.9

**Comment by arniebradfo** [comment]
I was planning on trying that in my next update. 

Would you happen to know how to fallback to a plugin version of codemirror if WP is less than 4.9?

**Comment by gr8shivam** [comment]
Added a pull request to validate the version.  It can be used like this:-

```
//Check if WP version is greater than 4.9
if($this->validate_version(4.9)){
	//Use CodeMirror script from WP
}
else{
	//Use CodeMirror script from Plugin
}
```

**Comment by gr8shivam** [comment]
@arniebradfo Hi, any updates on this?

**Comment by arniebradfo** [comment]
not yet. I'm waiting till next year. I'm buys right now. sorry.

**Comment by arniebradfo** [comment]
I've fixed this.

...also, your pull request wasn't even close to being working code. Please don't submit pull requests for pseudo code or whatever that was.

Thanks!
