### ISSUE TITLE
Option to disable auto-indent

### ISSUE THREAD

**Issue by Ixohoxi** [mukhortov/HESH-WordPress-Plugin#59]
I enjoy what this plugin does, but I would be delighted if auto-indent could be turned off!!

**Comment by arniebradfo** [comment]
Ill handle this and auto format here: #35

**Comment by arniebradfo** [comment]
Auto-indent is now disabled at [v2.3.2](https://github.com/mukhortov/HESH-WordPress-Plugin/releases/tag/v2.3.2).

If you're a regular user of this plugin, please consider taking a short [User Experience Survey](https://goo.gl/forms/xvaHgd7sZEbBbFAL2) to provide feedback that will help shape the new version 3.0.

Thanks!
