### ISSUE TITLE
Insert Image/Gallery Broken in 1.7

### ISSUE THREAD

**Issue by summit-web** [mukhortov/HESH-WordPress-Plugin#6]
Heya,

A few of us have left comments on your Wordpress support thread but the latest version has introduced a couple of bugs, one which makes using your plugin very difficult.

1. Inserting Image/Gallery in text/code mode fails
2. Pressing "Enter" inserts two new lines, rather than one.

As I don't have 1.6.9 backed up I'll have to deactivate your plugin, but as one of my sites is a code tutorial site I would appreciate (1) being fixed, please.
Thanks so much,

Martin

**Comment by arniebradfo** [comment]
The bugs have been fixed a development branch of the code base.

@mukhortov should release a patch shortly.

Thanks for brining this to our attention,
-James

**Comment by mukhortov** [comment]
Thanks @arniebradfo for the quick fix! And thanks @summit-web for opening the issue!

Going to release the updated version tonight.
