### ISSUE TITLE
How to use the plugin?

### ISSUE THREAD

**Issue by gegobyte** [mukhortov/HESH-WordPress-Plugin#60]
I installed this plugin because I wanted to highlight HTML, JS, CSS, PHP codes on my website. But there are literally no instructions on plugin page on how to use it. It just changes the background color of Wordpress post editor, not even sure how is that useful to anyone.

Let's say I have a code: <image src="image.jpg"> Now how to highlight so that the user can see it on the website? In the editor, there is no such option.

Do I need to embed the codes in a particular custom code so that the plugin will recognize it?

**Comment by arniebradfo** [comment]
This plugin is for the editor on the backend only. It does not do syntax highlighting on the frontend. sorry. 

[Try something from here maybe?](https://www.google.com/search?q=wordpress+code+snippet+syntax+highlighting&oq=wordpress+code+snippet)
