### ISSUE TITLE
Conflicts with WPBakery Page Builder – pages dont saves correctly

### ISSUE THREAD

**Issue by ambrosso** [mukhortov/HESH-WordPress-Plugin#61]
Hi, thanks for great plugin!

I have some errors when using this plugin with WPBakery Page Builder,
sometimes, when editing, pages dont saves correctly or dont even sage changes.

**Comment by arniebradfo** [comment]
Plugin Compatibility Issues are here: #28

**Comment by arniebradfo** [comment]
Is issue is tracked here now: #28
