### ISSUE TITLE
Auto indent

### ISSUE THREAD

**Issue by JNestudi** [mukhortov/HESH-WordPress-Plugin#64]
Is it possible to add the option to auto indent the code? It will clean the code and make easy the edition in post not new. When I create one post or page this plugging is the best but if the content is already on the DB is a bit of a mess...

**Comment by JNestudi** [comment]
Maybe I didn't explained myself... What I wnat is to format the code... to apply indent to the code to clarify the code... is it possible?

**Comment by arniebradfo** [comment]
Yes. This is the most requested feature, Ill add it next. 
Its here: #35
