### ISSUE TITLE
Please add "find and replace all" function

### ISSUE THREAD

**Issue by dolanb12** [mukhortov/HESH-WordPress-Plugin#67]
Hi and thanks for the great plugin!

This functionality would save a lot of time. Any way this could be implemented?

Thanks again!

**Comment by arniebradfo** [comment]
It is already implemented. I know it's not very straight forward, but you can follow these [key commands](https://codemirror.net/demo/search.html) to find and replace all.

**Comment by dolanb12** [comment]
Great! I didn't see this before. Thanks.
