### ISSUE TITLE
Highlight Conflict with the Footnotes Plugin

### ISSUE THREAD

**Issue by Blackhawke** [mukhortov/HESH-WordPress-Plugin#70]
There's this handy little plugin called "footnotation" that also uses square brackets. Unfortunately, because shortcodes are, well, *codes,* the punctuation put into a footnote often makes a complete mess of the code highlighting for the rest of the document.

Is there a way to "escape" (for lack of a better word) square brackets in certain cases so that it ignores the "code" in a footnote?

**Comment by arniebradfo** [comment]
I could add an exception just for this to the shortcode highlighter, but I think this [footnotation plugin](https://wordpress.org/plugins/footnotation/)'s syntax violates the [shortcodes API](https://codex.wordpress.org/Shortcode_API) in that the content in the brackets is not `attribute="value"` syntax. I think this might be too much effort on my end. Sorry.

You can escape shortcodes with a double bracket syntax like this: `[[escaped shortcode or whatever]]`, but this might screw up the way the footnotation plugin works.

**Comment by Blackhawke** [comment]
Thank you for that, especially the shortcode escape. I was wondering if there was one. The escape doesn't screw up the plugin, but it does put a square bracket around each footnote in the text. Still, they can be escaped, then *un*escaped during editing, so it's a decent work-around. (At this point, trying to find every bloody post and page on the site that has a foot note in it using the footnotation markup would be too much effort on *my* end. :)
