### ISSUE TITLE
Is err?

### ISSUE THREAD

**Issue by kee-work** [mukhortov/HESH-WordPress-Plugin#75]
https://github.com/mukhortov/HESH-WordPress-Plugin/blob/2e5caa1905bbf9ca878a8e4941f34c9d7b1c25f5/src/hesh.dev.js#L619

**Comment by arniebradfo** [comment]
Definitely an error. Thanks for finding this typo. What alerted you to it? Does it cause any bugs?

Will fix it asap

**Comment by arniebradfo** [comment]
_Fixed in [v2.2.5](https://github.com/mukhortov/HESH-WordPress-Plugin/releases/tag/v2.2.5)!_
