### ISSUE TITLE
Plugin Causes Server 500 Errors After Upgrading to Wordpress 5.0 

### ISSUE THREAD

**Issue by datagramsouth2016** [mukhortov/HESH-WordPress-Plugin#79]
Not a big deal, but after upgrading to Wordpress 5.0.2, I couldn't post or add new pages to my site, until I disabled this plugin. 

I re-enabled the plugin and it doesn't cause any 500 server errors, but the plugin itself isn't working on the post anymore.

**Comment by arniebradfo** [comment]
@datagramsouth2016 
I cannot recreate this issue. Would you mind checking to see if its still an issue in Wordpress 5.0.3?
Thanks!

**Comment by datagramsouth2016** [comment]
I will spin up a 4.8 and do the upgrade see if I can recreate it.

**Comment by arniebradfo** [comment]
@datagramsouth2016 Were you able to recreate the issue?

**Comment by arniebradfo** [comment]
@datagramsouth2016 I'm closing this issue. It doesn't seem to be related to this plugin.

If you're a regular user of this plugin, please consider taking a short [User Experience Survey](https://goo.gl/forms/xvaHgd7sZEbBbFAL2) to provide feedback that will help shape the new version 3.0.

Thanks!
