### ISSUE TITLE
We need (another) new release

### ISSUE THREAD

**Issue by arniebradfo** [mukhortov/HESH-WordPress-Plugin#9]
Peter,

There were some more bugs. Can you do another patch release? `v1.7.2`? Sorry they came a day too late for the other patch.

Thanks,
-James

**Comment by mukhortov** [comment]
Hey James,
Thanks for the changes! Good stuff
Could you create PRs instead of committing directly to the master so it would be possible to review and comment first? 

e.g. I don't think we should include dev files into the release version – https://github.com/mukhortov/HESH-WordPress-Plugin/blame/master/README.md#L152
or add technologies or libs we used to the plugin description – https://github.com/mukhortov/HESH-WordPress-Plugin/blob/master/readme.txt#L11

**Comment by arniebradfo** [comment]
Should we make the master branch the release branch, and open a dev branch with the build code?

I don't know what process you're going through to add this code to wordpress svn repository. I just assumed you were deleting everything but the .php, readme.txt, and libs files.

I think you're right about not including dev files in the final version, but the non-minified lib files are not currently in the dev folder as you mentioned [here](https://wordpress.org/support/topic/add-non-minfied-javascript-and-css-files). Just the prebuild files. Those files need to be compiled with other resources in the grunt build before they will function normally. I will add non minified versions of everything in the libs folder to the new development branch.

but...

I think the CodeMirror references will help with search. When I was initially looking for a syntax highlighting plugin, I used CodeMirror as a search term. When I was looking through the support forum, I found a post asking to [add codemirror as a tag](https://wordpress.org/support/topic/mention-codemirror) to make the plugin easier to find. Thought it could help, but if you really don't like it, revert those changes.

Thanks,
-James

**Comment by mukhortov** [comment]
> Should we make the master branch the release branch, and open a dev branch with the build code?

Master should stay as a dev branch, we don't use GH for the plugin distribution anyway. But would be easier to track and review changes with PRs and separate branches. We could create a new branch and a PR for every new plugin version and merge to master once it's ready. Pretty much a [GitHub workflow](https://guides.github.com/introduction/flow/). What do you think?

> but the non-minified lib files are not currently in the dev folder as you mentioned here

Are you sure? I can see all the dev files in the dev SVN trunk https://plugins.svn.wordpress.org/html-editor-syntax-highlighter/trunk/dev/

> I think the CodeMirror references will help with search. When I was initially looking for a syntax highlighting plugin, I used CodeMirror as a search term.

Ok, I didn't even think that anyone would search for CodeMirror thinking about syntax highlighting plugin :) Let's leave it then.
